### ISSUE TITLE
Unclutter the repository

### ISSUE THREAD

**Issue by sujaldev** [TriAay249/JEEPYQREPLYBOT#9]
Right now all the files are in the project root which is fine, but as the project grows it'll have a lot of files that aren't part of the source code so we should move all the source code to a new `src/` directory.

Another thing I want to suggest is that we should follow pep8 style guides (it will keep the commits a lot more tidy as each commit won't have bunch of whitespace changes) or a maybe a configuration file, which IDE/text-editor do you use?

**Comment by TriAay249** [comment]
Done. I use Visual Studio Code.

**Comment by sujaldev** [comment]
I don't use vscode but I found [this](https://code.visualstudio.com/docs/python/editing#_formatting), maybe this will enforce pep8 guidelines.
